### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by TingPing** [flathub/org.gnome.Eolie#26]
```python
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/eolie/application.py", line 142, in do_startup
    self.__init()
  File "/app/lib/python3.7/site-packages/eolie/application.py", line 346, in __init
    self.update_default_style_sheet()
  File "/app/lib/python3.7/site-packages/eolie/application.py", line 128, in update_default_style_sheet
    rules = self.adblock.get_default_css_rules()
  File "/app/lib/python3.7/site-packages/eolie/database_adblock.py", line 237, in get_default_css_rules
    result = sql.execute(request)
sqlite3.OperationalError: no such table: adblock_css
```

**Comment by nedrichards** [comment]
now launches!
